### ISSUE TITLE
[Question] ViewModels notified about state change outside of a view

### ISSUE THREAD

**Issue by dchohfi** [sergdort/CombineFeedback#18]
Hey, this is a really interesting library, simple and nice to use, but I'm having hard times trying to figure out how to share data between multiple views.

What is the best approach to communicate state change and get feedbacks outside of a View/ViewModel?

Should it be done subscribing  to the `state: AnyPublisher<State, Never>` property of the view model? Or sending a `Feedback` to the view model?

**Comment by sergdort** [comment]
What I would recommend is to have some kind of `ContainerView` like React-Redux [does](https://redux.js.org/basics/usage-with-react#presentational-and-container-components)

So you have like a `ContainerView` which acts like an adapter between your component views by transforming the state of the `ViewModel` into presentable way (doing some formatting etc) to able to display it in your `ComponentView`. Regarding user input you can do that by using `Binding` or plain callbacks to inform you `ViewModel` about user input

```swift
ContainerView(context: Context<State, Event>) {
    let context: Context<State, Event>

    var body: some View {
        return VStack {
            MyComponent(context.title, didTap: context.action(Event.someEvent),
            MyOtherComponent(context.detail, input: context.binding(\.detail))
        }
    }
} 
```

**Comment by grinder81** [comment]
What is your recommendation then for the following image is state in my app:

<img width="492" alt="Screen Shot 2019-11-20 at 3 20 37 PM" src="https://user-images.githubusercontent.com/759257/69274908-5b751600-0ba9-11ea-9943-da1900e1f3f5.png">

Here is the AppState code which mean you can go deep nested state of your app:

<img width="564" alt="Screen Shot 2019-11-20 at 3 24 59 PM" src="https://user-images.githubusercontent.com/759257/69275315-25846180-0baa-11ea-8da6-e93867b47b4c.png">

For reference here is my AppView code which is the root view:

<img width="1227" alt="Screen Shot 2019-11-20 at 3 22 03 PM" src="https://user-images.githubusercontent.com/759257/69275410-52d10f80-0baa-11ea-8545-dee69c1b57ee.png">

Now problem is, my login view completed login and change the state, that only visible in that view and at max we can I can bind with another view like you showed but I can't change my top App State which should load different view component like my HomeView.

Do you have any idea how you can manage your global state of your app? All the example you have only care about single view but real app is more complex with many depth and changing state from bottom to up.

**Comment by sergdort** [comment]
@grinder81 @dchohfi  I've added an example yesterday of having single store for multiple views it's in the `SingleStoreExample` folder.
Let me know if anything is unclear

**Comment by grinder81** [comment]
Thanks a lot @sergdort I'm doing some details analysis on your example. I found one thing strange is your  `SingleStoreExampleView` render never stops though there is no local state change. That's true for internal state live `MovieView` as well. Basically looks like a constant render call is going on which is redundant. I believe `Context` is mutating the state or something. Let me know your thoughts. Thanks for your effort.

**Comment by grinder81** [comment]
After doing more investigation, I think major problem is, you won't be able to unsubscribe a `Feedback` when you are done with corresponding sub-system. Wen you pullback from local state to global state, you must need ability to unmount sub-state, otherwise it will keep going to emit event and pullback reducer and feedback won't stop. That's my understanding so far.

**Comment by sergdort** [comment]
Hey @grinder81, thanks for your investigations!
I think that I found an "issue" which is not an issue :) because if you look on the 4th tab there is an example of "traffic light" system which is changing its state with some behaviour (timer) so it cause the whole state to change which cause the rendering. But I'm afraid that is how every `ReduxUI` based frameworks work (e.g even if the substate changes it re-renders the whole thing) it's just `SwiftUI` and `React` are smart enough to handle the diffing.
